### ISSUE TITLE
Slack notifications fails when workflow permission is set to read

### ISSUE THREAD

**Issue by MohamadTahir** [Gamesight/slack-workflow-status#22]
Hey, so I am failing to send notifications to my slack channel. after invistegating the problem I found out that the task is failing because I've changed my repo settings.

Go to `settings >> actions >> general` then under `Workflow permissions` choose `Read repository contents permission` doing that the slack notification will fail to send notifications.

I've tried to create a costume access token, when I create a token that has full access to the repo the workflow works fine and notifications are sent

```
 repo : Full control of private repositories
``` 

but if I don't give a full access to the repo the job will fail, even if I select all of the sub categories underneath the repo permission

```
 repo:status : Access commit status
 repo_deployment : Access deployment status
 public_repo : Access public repositories
 repo:invite : Access repository invitations
 security_events : Read and write security events
```

I am giving it the same access levels as the repo permission but it is still failing. I've checked the source code and as far as I can see you're requesting only read access? but I don't know why the job is failing.

To make it short,  I do not want to give a full access token to the workflow.  to send slack notification.

**Comment by AnthonyKinson** [comment]
Hey, @MohamadTahir thanks for taking the time to create an issue, that is very strange. I'm not sure if something changed somewhere but i'll certainly look into this!
