### ISSUE TITLE
Show last commit on Slack

### ISSUE THREAD

**Issue by dcelasun** [Gamesight/slack-workflow-status#4]
Thanks for maintaining this action!

Would it be possible to include the last commit on Slack? For example:

```
Success: dcelasun's pull_request #1 from new-feature to master
Workflow: test-and-deploy #123 completed in 1m 2s
Commit: First line of commit message (096e807)
```
and the commit hash would be a link to the commit.

**Comment by AnthonyKinson** [comment]
That should be possible. I'll have a look at throwing that in as a configurable option.
