### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by harikrishnatrkv** [Gamesight/slack-workflow-status#52]
Hi

Getting warning from the workflow.

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Gamesight/slack-workflow-status@v1.1.0`

Please help to fix

**Comment by harikrishnatrkv** [comment]
Use Gamesight/slack-workflow-status@master  instead of Gamesight/slack-workflow-status@v1.1.0  to disable the warning

**Comment by AnthonyKinson** [comment]
new release @ v1.2.0 now uses node16 and should remove those deprecation notifications.
