### ISSUE TITLE
PR link to GitHub api url

### ISSUE THREAD

**Issue by swfz** [Gamesight/slack-workflow-status#8]
I'm comfortable with it!

I found a problem that when you click on a PR number, you are redirected to the URL of the API, so I checked the repository, and it seems that the following PRs are used

https://github.com/Gamesight/slack-workflow-status/commit/9cc863f8369fe43931daff811fb17c55b5a5c4eb

I'd like to use it, so I'd like you to type a version of tag with the above fix applied

**Comment by AnthonyKinson** [comment]
The master branch should have those fixes, I've created a new release tag which contains all the latest security patches and PR link fix here [v1.0.1](https://github.com/Gamesight/slack-workflow-status/releases/tag/v1.0.1)
